config/routes.rb
Rails.application.routes.draw do
  # Root
  root "dashboard#index"

  # Products
  resources :products do
    member do
      get :new_movement
      post :create_movement
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movement.rb
class Movement < ApplicationRecord
  # Movement Types
  MovementTypes = { add: 0, remove: 1 }

  # Associations
  belongs_to :product

  # Validates
  validates :quantity, presence: true, numericality: true

  def self.get_movement_types
    {
      'Add' => MovementTypes[:add],
      'Remove' => MovementTypes[:remove]
    }
  end

  def type_name
    return "Add" if movement_type == MovementTypes[:add]
    return "Remove" if movement_type == MovementTypes[:remove]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # Associations
  has_many :movements

  # Validates
  validates :name, :reference, :description, presence: true

  def quantity
    total = 0
    self.movements.each do |movement|
      if movement.movement_type == Movement::MovementTypes[:add]
        total += movement.quantity
      else
        total -= movement.quantity
      end
    end
    return total
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.xlsx{
        response.headers['Content-Disposition'] = 'attachment; filename="List of Products.xlsx"'
      }
    end
  end

  # GET /products/1 or /products/1.json
  def show
    respond_to do |format|
      format.html
      format.xlsx{
        response.headers['Content-Disposition'] = 'attachment; filename="Details Product.xlsx"'
      }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_movement
    set_product
    @movement = Movement.new
  end

  def create_movement
    set_product
    @movement = Movement.new(movement_params)
    @movement.product_id = @product.id
    if @movement.save
      redirect_to @product, notice: "The movement was created."
    else
      flash[:notice] = 'An error occurred while creating the movement.'
      render :new_movement, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :reference, :description)
    end

    def movement_params
      params.require(:movement).permit(:movement_type, :quantity, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mi Bodega</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="<%= products_path %>">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Products</span>
        </a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <%= yield %>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with(model: product) do |form| %>
        <% if product.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
              <% product.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>

        <div class="form-group">
          <%= form.label :reference, style: "display: block" %>
          <%= form.text_field :reference, class: "form-control", placeholder: "Reference" %>
        </div>

        <div class="form-group">
          <%= form.label :description, style: "display: block" %>
          <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
        </div>

        <div>
          <%= form.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Reference:</strong>
    <%= product.reference %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product, class: "btn btn-primary" %>
  <%= link_to "Back to products", products_path, class: "btn btn-secondary" %>
</div>

app/views/products/index.html.erb
<h1>List of Products</h1>

<div class="d-flex align-content-center mb-4">
  <a href="<%= new_product_path %>" class="btn btn-primary btn-icon-split mr-2">
    <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
    </span>
    <span class="text">New Product</span>
  </a>

  <%= link_to "Export excel", products_path(format: :xlsx), class: "btn btn-danger" %>
</div>


<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Reference</th>
      <th>Amount</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.reference %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to "Details", product_path(product), class: "btn btn-primary" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New product</h1>
<div>
  <%= link_to "Back to products", products_path, class: "btn btn-primary mb-4" %>
</div>

<%= render "form", product: @product %>

app/views/products/new_movement.html.erb
<h1>Create Movement</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <table class="table">
        <tr>
          <td><b>Name:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Reference:</b></td>
          <td><%= @product.reference %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="row mt-4">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @movement, url: create_movement_product_path(@product) do |f| %>
        <% if @movement.errors.any? %>
          <div class="alert alert-danger">
            <h3><%= flash[:notice] %></h3>
            <ul>
              <% @movement.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :movement_type, "Type of movement:" %>
          <%= f.select :movement_type, options_for_select(Movement.get_movement_types), {}, { class: "form-control" } %>
        </div>

        <div class="form-group">
          <%= f.label :quantity, "Quantity:" %>
          <%= f.number_field :quantity, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :comment, "Comments:" %>
          <%= f.text_area :comment, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Cancel", product_path(@product), class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div class="row">
  <div class="col-lg-12">
    <h1>Details Product</h1>

    <div class="d-flex mb-4">
      <%= link_to "Back to products", products_path, class: "btn btn-primary mr-2" %>
      <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-primary mr-2" %>
      <%= button_to "Destroy this product", @product, method: :delete, class: "btn btn-danger mr-2" %>
      <%= link_to "Create Movement", new_movement_product_path(@product), class: "btn btn-success mr-2" %>
      <%= link_to "Export excel", product_path(@product, format: :xlsx), class: "btn btn-danger" %>
    </div>

    <div class="card">
      <table class="table">
        <tr>
          <td><b>Name of product:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Reference:</b></td>
          <td><%= @product.reference %></td>
        </tr>
        <tr>
          <td><b>Desciption:</b></td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td><b>Amount:</b></td>
          <td><%= @product.quantity %></td>
        </tr>
        <tr>
          <td><b>Created at:</b></td>
          <td><%= @product.created_at.strftime("%F") %></td>
        </tr>
      </table>
    </div>

  </div>
</div>

<div class="row mt-4">
  <div class="col-lg-12">
    <div class="card">
      <h1>Movements</h1>
      <table class="table">
        <thead>
        <tr>
          <th>Type</th>
          <th>Amount</th>
          <th>Comment</th>
          <th>Date/Time</th>
        </tr>
        </thead>
        <tbody>
          <% @product.movements.each do |movement| %>
            <tr>
              <td><%= movement.type_name %></td>
              <td><%= movement.quantity %></td>
              <td><%= movement.comment %></td>
              <td><%= movement.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>